# Map git commands through hub
if [ -e /usr/local/bin/hub ]; then 
  alias git=hub
fi

# Use MacVim's version of the Vim executable instead of the systems
if [ -e /usr/local/bin/brew ]; then 
  MACVIM_BASE=`brew --cellar macvim`
  MACVIM_VERSION=`brew versions macvim --compact | cut -d ' ' -f 1`
  alias vim='$MACVIM_BASE/$MACVIM_VERSION/MacVim.app/Contents/MacOS/Vim'
fi

# Open Apps
alias safari='open -a Safari'
alias firefox='open -a FireFox'
alias chrome='open -a Google\ Chrome'
alias propane='open -a Propane'
alias preview='open -a Preview'
alias itunes='open -a iTunes'

# Handy stuff
alias reload="source ~/.bash_profile && cd ../ && cd -"
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls -G'
alias la='ls -lA'
alias ll='ls -l'
alias las='ls -lAS'
alias hi='history | tail -50'
alias be='bundle exec'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

